name: ragamala-sdxl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
  - defaults

dependencies:
  # Python version
  - python=3.10

  # Core Deep Learning Frameworks
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8

  # NVIDIA GPU Support
  - nvidia::cuda-toolkit=11.8
  - nvidia::cudnn=8.7.0

  # Core Scientific Computing
  - numpy>=1.24.0
  - scipy>=1.11.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Computer Vision and Image Processing
  - opencv>=4.8.0
  - pillow>=10.0.0
  - scikit-image>=0.21.0
  - imageio>=2.31.0

  # Jupyter and Development Environment
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.25.0
  - ipywidgets>=8.1.0
  - notebook>=7.0.0

  # Configuration and Utilities
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - requests>=2.31.0
  - click>=8.1.0

  # Database Support
  - sqlalchemy>=2.0.0
  - psycopg2>=2.9.0

  # Development Tools
  - black>=23.7.0
  - isort>=5.12.0
  - flake8>=6.0.0
  - pytest>=7.4.0
  - pre-commit>=3.3.0

  # System Monitoring
  - psutil>=5.9.0

  # File Format Support
  - openpyxl>=3.1.0
  - jsonlines>=3.1.0

  # Web Framework Dependencies
  - jinja2>=3.1.0
  - aiofiles>=23.1.0

  # Async Support
  - aiohttp>=3.8.0

  # Cloud Storage
  - boto3>=1.28.0
  - s3fs>=2023.6.0

  # Redis for Caching
  - redis-py>=4.6.0
  - hiredis>=2.2.0

  # Text Processing
  - nltk>=3.8.0

  # Visualization
  - plotly>=5.15.0
  - bokeh>=3.2.0

  # Performance Optimization
  - numba>=0.58.0

  # Docker Support
  - docker-py>=6.1.0

  # Development and Debugging
  - ipdb>=0.13.0
  - line_profiler>=4.1.0
  - memory_profiler>=0.61.0

  # Pip dependencies that are not available in conda
  - pip>=23.0.0
  - pip:
    # Hugging Face Ecosystem
    - transformers>=4.30.0
    - diffusers>=0.21.0
    - accelerate>=0.20.0
    - datasets>=2.14.0
    - huggingface-hub>=0.16.0
    - peft>=0.4.0

    # SDXL Specific Dependencies
    - safetensors>=0.3.1
    - compel>=2.0.0
    - invisible-watermark>=0.2.0
    - omegaconf>=2.3.0
    - xformers>=0.0.20

    # Computer Vision and Evaluation
    - albumentations>=1.3.0
    - clip-by-openai>=1.0
    - lpips>=0.1.4
    - pytorch-fid>=0.3.0
    - torchmetrics>=1.0.0
    - cleanfid>=0.1.35

    # Web Framework and API
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.23.0
    - pydantic>=2.0.0
    - python-multipart>=0.0.6

    # Authentication and Security
    - python-jose[cryptography]>=3.3.0
    - passlib[bcrypt]>=1.7.4

    # Rate Limiting
    - slowapi>=0.1.9

    # Frontend and Visualization
    - gradio>=3.40.0
    - streamlit>=1.25.0

    # Logging and Monitoring
    - wandb>=0.15.0
    - tensorboard>=2.13.0
    - mlflow>=2.5.0
    - loguru>=0.7.0

    # Configuration Management
    - python-dotenv>=1.0.0
    - hydra-core>=1.3.0

    # Testing Framework Extensions
    - pytest-asyncio>=0.21.0
    - pytest-cov>=4.1.0
    - httpx>=0.24.0

    # Type Checking
    - mypy>=1.5.0

    # Utilities
    - rich>=13.5.0
    - typer>=0.9.0

    # Cultural and Text Processing
    - indic-transliteration>=2.3.0
    - spacy>=3.6.0

    # Performance Monitoring
    - gpustat>=1.1.0
    - py-cpuinfo>=9.0.0

    # Cloud Providers
    - google-cloud-storage>=2.10.0
    - azure-storage-blob>=12.17.0

    # Kubernetes Support
    - kubernetes>=27.2.0

    # Database Migration
    - alembic>=1.11.0

    # File Format Support
    - xlsxwriter>=3.1.0

    # Art and Cultural Specific Libraries
    - musicpy>=1.5.0

    # Additional Development Tools
    - urllib3>=2.0.0

# Environment Variables
variables:
  CUDA_VISIBLE_DEVICES: "0"
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512"
  TOKENIZERS_PARALLELISM: "false"
  WANDB_PROJECT: "ragamala-sdxl"
  HUGGINGFACE_HUB_CACHE: "/tmp/huggingface_cache"
  TRANSFORMERS_CACHE: "/tmp/transformers_cache"
  HF_HOME: "/tmp/huggingface"
